### ISSUE TITLE
Question bank

### ISSUE THREAD

**Issue by matthewdoles** [quasney24/felixGames#16]
Thoughts on hosting a question bank in firebase or elsewhere ourselves? The API says they switch out questions regularly (like every 6 hours maybe), but I'm finding alot of repeats. Also some of the questions seem to decode poorly.  In addition, we wouldn't have to deal with some of the weird error handling with that API.

Perhaps we could still scrape their API and add new questions to our bank (if that is okay?). But with our own question bank, we could do some neat features like capture analytics on how other users have performed on the same question. And we could also allow other users to submit their own questions for review.

**Comment by quasney24** [comment]
I think that is a great idea. Would be cool to build some admin web portal or something to maintain questions coming in. I wonder how we would scrape the database tho since we can only pull 1 category at a time and only 50 questions.

**Comment by matthewdoles** [comment]
Moving to done. We have started tackling this and have built out an initial implementation in a dedicated backed service layer: https://github.com/matthewdoles/felix-games-service
